### ISSUE TITLE
BlockingWaitStrategy is not blocking enough.

### ISSUE THREAD

**Issue by alewmt** [disruptor-net/Disruptor-net#35]
Hi! Found strange behavior. Sending a heartbeat message every second to a disruptor lead to 100% cpu load without any useful work.

Environment: AWS VM m4.large, 2 core 2.3GHz, Disruptor 3.3.5.1

Count of sent messages is 78 :

![image](https://user-images.githubusercontent.com/9164890/40991526-b98518f4-68fc-11e8-9057-5b3b4e52a41d.png)

![image](https://user-images.githubusercontent.com/9164890/40991648-16b3106c-68fd-11e8-97d9-6aaba910b53f.png)

Is it a bug or by design?

**Comment by alewmt** [comment]
I found out that the problem exists with chained handlers like this:
```
disruptor.HandleEventsWith(new Handler1())
                .Then(new Handler2())
                .Then(new Handler3())
                .Then(new Handler4());
```
An every next handler eats cpu more than previous

![image](https://user-images.githubusercontent.com/9164890/41010007-8678a76e-693d-11e8-9639-92831c415b3e.png)

I think this is a serious problem. Dependent handlers chaining is a most valuable disruptor feature. The more cores required, the less efficient became an application just because last handlers in a chain start eat cpu too early.

/cc @mikeb01 @mjpt777

**Comment by ocoanet** [comment]
Hi.

High CPU usage caused by waiting dependent handlers is a [known issue](https://github.com/disruptor-net/Disruptor-net/issues/25) in the .NET and Java version.

Once an event is published, dependent handlers will spin-wait until previous handlers have processed the event. You should observe high CPU usage when an event is being processed. In your scenario, you should normally get CPU spikes every second like this:

![image](https://user-images.githubusercontent.com/1525572/41025752-0e703094-6973-11e8-868b-1c1879805439.png)

Be aware that many tools (e.g., Task Manager or Process Explorer) will incorrectly show permanent high CPU usage in this situation.

I added `BlockingSpinWaitWaitStrategy` in 3.3.6 to reduce CPU usage with chained handlers. I also improved `BlockingWaitStrategy` in 3.3.6 by using an `AggressiveSpinWait` to perform the spin-wait.

Hope this helps.

**Comment by alewmt** [comment]
Thank you. It really helped.

> Be aware that many tools (e.g., Task Manager or Process Explorer) will incorrectly show permanent high CPU usage in this situation.

I didn't know that. Is there a tool which shows actual level of cpu usage?

**Comment by ocoanet** [comment]
>  Is there a tool which shows actual level of cpu usage?

Anything that is ETW-based will provide more accurate results. You can use WPA for example. Or if you like dotTrade, just choose the Timeline profiling option.
