### ISSUE TITLE
Q: Send message to self

### ISSUE THREAD

**Issue by et1975** [disruptor-net/Disruptor-net#41]
I'd like my consumer to send a message to itself now and then. 
I just found that it's not safe to do so - if my buffer is dominated by messages to self the buffer stops processing - the capacity shrinks at every publish to self. There was a mention on stackoverflow of "custom event handler" that would make it possible to mark the message as processed, but I don't see how it can be done - not in the Java version, nor in .NET.
I tried introducing another disruptor in between, so that I don't publish directly into my own buffer, but that doesn't seem to help. Looking for ideas.

**Comment by ocoanet** [comment]
Hello Eugene,

Self-enqueuing is indeed a known issue and a bad practice. When the ring buffer is full, the call to `RingBuffer.Next` is blocking to generate backpressure. Thus, the call to `Next` can deadlock if data is published by the consumer (event handler) thread.

There are multiple options to deal with this behavior:

1. **Do not self-enqueue**

Self-enqueuing only makes sense if the current event handler is not first handler or if you want to process the data after the previously published events. If the current event handler is the first and the new event can be processed right away, you can easily process it synchronously.

If your new event must be processed after the previously published events, you can retrieve the last published sequence number, save the new event in your event handler state, and process it synchronously during the `OnEvent` of the retrieved sequence number.

2. **Use `TryNext` instead of `Next`**

You can prevent the deadlock by using `RingBuffer.TryNext` and handling the case when the ring buffer is full. Of course, it is only interesting if you can handle this case. Is it acceptable to drop the event? Or can you allocate and run the publication in a thread-pool thread using `Task.Run`? Note that the latter is simply an easy way to add an indirection layer.

3. **Add an indirection layer**

You can publish your event to another queue or ring buffer. The ring buffer is preferable for performance reasons, but you can also opt for a simple ConcurrentQueue + ValueType combination.

I hope this helps.

**Comment by et1975** [comment]
Thank you for taking the time and the detailed response!
The option 3 is what I tried to do and what I see (and, in retrospect, is not surprising) is that publishing and event handling happens synchronously on the same thread so I'm not gaining anything by this indirection. And if I could tell disruptor to process the events asynchronously then it seems I would not have this problem to begin with?

**Comment by et1975** [comment]
On related topic, even when publishing to itself via a separate thread `GetRemainingCapacity()` once reaches zero, stays at 0, yet it doesn't prevent `ringBuffer.Next()` from returning with the next seq#. Am I misunderstanding what this number means?

**Comment by ocoanet** [comment]
> what I see (and, in retrospect, is not surprising) is that publishing and event handling happens synchronously on the same thread

It should not be the case. If you are self-enqueuing, publishing and event handling will happen on the same thread, but not synchronously. The published event will indeed be processed on the same thread but on a subsequent call to `OnEvent`.

If you are publishing an event to another Disruptor, publishing and event handling will never happen on the same thread.

Could you please describe your Disruptor configuration? How many event handlers do you have? Why do you need to self-enqueue? What is the rate of self-enqueuing?

From my experience:

- Self-enqueuing from the first event handler is probably a mistake or a design error.
- Self-enqueuing from a following event handler is an anti-pattern. Like every anti-pattern, it can be justified in some situations. Yet, the chances are that it is not justified in your situation.

**Comment by et1975** [comment]
You are right of course, it's not really synchronous, but for backpressure to function it has to appear as such eventually. 
My application of disruptor is re-implementation of a small subset of Storm for the purpose of running .NET components in-proc. So, conceptually, I have a cyclic processing graph - ack/nack from downstream components/bolts will be sent back to the source/spout. But the immediate problem is that I need something like `OnIdle` that would keep the source busy in absence of other commands. I've been faking it by feeding the source with commands whenever its event handler reaches "end of batch", but you know how it plays out.
My current instinct is to implement a wait strategy that can feed the source on idle, what do you think?

**Comment by ocoanet** [comment]
There are already timeout based wait strategies that will notify your event handler periodically in the absence of events. See `TimeoutBlockingWaitStrategy` and `ITimeoutHandler`. Note that the timeouts are currently implemented using exceptions, so the performance is not on a par with the rest of the Disruptor components.

>  I've been faking it by feeding the source with commands whenever its event handler reaches "end of batch", but you know how it plays out.

You are basically enqueuing a new event every time you process an event, this is clearly a very bad idea. You could at least try to enqueue only when the queue is empty. But the timeout based solution seems more appropriate. It would be possible to add an optional `OnIdle` callback but that would make your event handler busy spin and continuously consume a core.

**Comment by et1975** [comment]
Thank you.
