### ISSUE TITLE
EventPoller for ValueRingBuffer

### ISSUE THREAD

**Issue by williamk17** [disruptor-net/Disruptor-net#48]
Hi there,

I have something already implemented with RingBuffer together with the EventPoller. I'm trying to migrate events from classes to structs but stuck as there isn't an EventPoller for ValueRingBuffer.

I find the EventPoller useful because I have a single thread handling events from multiple RingBuffers.

What is the best way to do this if EventPoller isn't available for ValueRingBuffer? Happy to help implementing it if this is the way to go.

Thanks for the great work!

**Comment by ocoanet** [comment]
I think that I was too lazy to port the EventPoller in the ValueRingBuffer and I was waiting for someone to need it 🙂.
I will look into the possible implementations tomorrow and I will let you know if I need some help.
It turns out I was planning to refactor the EventPoller because its performances are not on par with BatchEventProcessor.

**Comment by williamk17** [comment]
Thanks for looking into this. Happy to contribute.

**Comment by ocoanet** [comment]
The EventPoller was added for the ValueRingBuffer. It will be available in the next major version.Are you interested in a pre-release?

**Comment by williamk17** [comment]
Thanks so much! Yes I'm interested in a pre-release.

**Comment by ocoanet** [comment]
It should be available in the [4.0.0-beta](https://www.nuget.org/packages/Disruptor/4.0.0-beta).
